# Generated by Django 5.0.6 on 2024-07-23 06:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='vent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ventify_app.vent'),
        ),
    ]
